// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx2J53iuRYBgD4sSWPo4GSFxiON2f7p8E',
    appId: '1:365594723048:web:3052b991ffb4cb74093f5d',
    messagingSenderId: '365594723048',
    projectId: 'pushnotification-e343e',
    authDomain: 'pushnotification-e343e.firebaseapp.com',
    storageBucket: 'pushnotification-e343e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrXXG6qpIr6sHB3bPKGrEAm0ne_K6soW4',
    appId: '1:365594723048:android:aa410e2f86ff8390093f5d',
    messagingSenderId: '365594723048',
    projectId: 'pushnotification-e343e',
    storageBucket: 'pushnotification-e343e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFpgOixyGO8osTNqVIOlqlCw7Wd1Wn9XY',
    appId: '1:365594723048:ios:dfc517e97cd3d8e6093f5d',
    messagingSenderId: '365594723048',
    projectId: 'pushnotification-e343e',
    storageBucket: 'pushnotification-e343e.firebasestorage.app',
    iosBundleId: 'com.example.pushNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFpgOixyGO8osTNqVIOlqlCw7Wd1Wn9XY',
    appId: '1:365594723048:ios:dfc517e97cd3d8e6093f5d',
    messagingSenderId: '365594723048',
    projectId: 'pushnotification-e343e',
    storageBucket: 'pushnotification-e343e.firebasestorage.app',
    iosBundleId: 'com.example.pushNotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDx2J53iuRYBgD4sSWPo4GSFxiON2f7p8E',
    appId: '1:365594723048:web:38105efcfbee99f0093f5d',
    messagingSenderId: '365594723048',
    projectId: 'pushnotification-e343e',
    authDomain: 'pushnotification-e343e.firebaseapp.com',
    storageBucket: 'pushnotification-e343e.firebasestorage.app',
  );
}
